In [1]:
import pandas as pd

In [2]:
air_2021 = pd.read_csv('../Datasets/annual_conc_by_monitor_2021.csv')

In [3]:
air_2021.columns = air_2021.columns.str.replace(' ', '_')

In [12]:
county = 'Los Angeles'

test = air_2021.query('County_Name == @county and Parameter_Name == "PM2.5 - Local Conditions"')
for col in test:
    if len(test[col].value_counts()) > 1:
        print(col)
        print(test[col])

Site_Num
9368        2
9369        2
9370        2
9371        2
9372        2
         ...
10496    9033
10497    9033
10498    9033
10499    9033
10500    9033
Name: Site_Num, Length: 111, dtype: int64
POC
9368     1
9369     1
9370     1
9371     1
9372     1
        ..
10496    1
10497    1
10498    1
10499    1
10500    1
Name: POC, Length: 111, dtype: int64
Latitude
9368     34.136500
9369     34.136500
9370     34.136500
9371     34.136500
9372     34.136500
           ...
10496    34.669739
10497    34.669739
10498    34.669739
10499    34.669739
10500    34.669739
Name: Latitude, Length: 111, dtype: float64
Longitude
9368    -117.923910
9369    -117.923910
9370    -117.923910
9371    -117.923910
9372    -117.923910
            ...
10496   -118.130511
10497   -118.130511
10498   -118.130511
10499   -118.130511
10500   -118.130511
Name: Longitude, Length: 111, dtype: float64
Datum
9368     WGS84
9369     WGS84
9370     WGS84
9371     WGS84
9372     WGS84
         ...
10496    NAD83
10497    NAD83
10498    NAD83
10499    NAD83
10500    NAD83
Name: Datum, Length: 111, dtype: object
Sample_Duration
9368           24 HOUR
9369           24 HOUR
9370           24 HOUR
9371           24 HOUR
9372           24 HOUR
             ...
10496    24-HR BLK AVG
10497    24-HR BLK AVG
10498    24-HR BLK AVG
10499    24-HR BLK AVG
10500    24-HR BLK AVG
Name: Sample_Duration, Length: 111, dtype: object
Pollutant_Standard
9368     PM25 24-hour 1997
9369     PM25 24-hour 2006
9370     PM25 24-hour 2012
9371      PM25 Annual 1997
9372      PM25 Annual 2006
               ...
10496    PM25 24-hour 2006
10497    PM25 24-hour 2012
10498     PM25 Annual 1997
10499     PM25 Annual 2006
10500     PM25 Annual 2012
Name: Pollutant_Standard, Length: 111, dtype: object
Metric_Used
9368                         Daily Mean
9369                         Daily Mean
9370                         Daily Mean
9371     Quarterly Means of Daily Means
9372     Quarterly Means of Daily Means
                      ...
10496                        Daily Mean
10497                        Daily Mean
10498    Quarterly Means of Daily Means
10499    Quarterly Means of Daily Means
10500    Quarterly Means of Daily Means
Name: Metric_Used, Length: 111, dtype: object
Method_Name
9368     R & P Model 2000 PM-2.5 Air Sampler w/VSCC - G...
9369     R & P Model 2000 PM-2.5 Air Sampler w/VSCC - G...
9370     R & P Model 2000 PM-2.5 Air Sampler w/VSCC - G...
9371     R & P Model 2000 PM-2.5 Air Sampler w/VSCC - G...
9372     R & P Model 2000 PM-2.5 Air Sampler w/VSCC - G...
                               ...
10496                                                  NaN
10497                                                  NaN
10498                                                  NaN
10499                                                  NaN
10500                                                  NaN
Name: Method_Name, Length: 111, dtype: object
Event_Type
9368     No Events
9369     No Events
9370     No Events
9371     No Events
9372     No Events
           ...
10496    No Events
10497    No Events
10498    No Events
10499    No Events
10500    No Events
Name: Event_Type, Length: 111, dtype: object
Observation_Count
9368      59
9369      59
9370      59
9371      59
9372      59
        ...
10496    359
10497    359
10498    359
10499    359
10500    359
Name: Observation_Count, Length: 111, dtype: int64
Observation_Percent
9368     97
9369     97
9370     97
9371     97
9372     97
         ..
10496    98
10497    98
10498    98
10499    98
10500    98
Name: Observation_Percent, Length: 111, dtype: int64
Completeness_Indicator
9368     Y
9369     Y
9370     Y
9371     Y
9372     Y
        ..
10496    Y
10497    Y
10498    Y
10499    Y
10500    Y
Name: Completeness_Indicator, Length: 111, dtype: object
Valid_Day_Count
9368      59
9369      59
9370      59
9371      59
9372      59
        ...
10496    359
10497    359
10498    359
10499    359
10500    359
Name: Valid_Day_Count, Length: 111, dtype: int64
Required_Day_Count
9368      61
9369      61
9370      61
9371      61
9372      61
        ...
10496    365
10497    365
10498    365
10499    365
10500    365
Name: Required_Day_Count, Length: 111, dtype: int64
Exceptional_Data_Count
9368     0
9369     0
9370     0
9371     0
9372     0
        ..
10496    0
10497    0
10498    0
10499    0
10500    0
Name: Exceptional_Data_Count, Length: 111, dtype: int64
Null_Data_Count
9368     2
9369     2
9370     2
9371     2
9372     2
        ..
10496    0
10497    0
10498    0
10499    0
10500    0
Name: Null_Data_Count, Length: 111, dtype: int64
Primary_Exceedance_Count
9368      0.0
9369      2.0
9370      2.0
9371      NaN
9372      NaN
         ...
10496     1.0
10497     1.0
10498    19.0
10499     NaN
10500     NaN
Name: Primary_Exceedance_Count, Length: 111, dtype: float64
Secondary_Exceedance_Count
9368      0.0
9369      2.0
9370      2.0
9371      NaN
9372      NaN
         ...
10496     1.0
10497     1.0
10498    19.0
10499     NaN
10500     NaN
Name: Secondary_Exceedance_Count, Length: 111, dtype: float64
Certification_Indicator
9368     Certified
9369     Certified
9370     Certified
9371     Certified
9372     Certified
           ...
10496    Certified
10497    Certified
10498    Certified
10499    Certified
10500    Certified
Name: Certification_Indicator, Length: 111, dtype: object
Arithmetic_Mean
9368     12.157627
9369     12.157627
9370     12.157627
9371     12.157627
9372     12.157627
           ...
10496     8.108357
10497     8.108357
10498     8.108357
10499     8.108357
10500     8.108357
Name: Arithmetic_Mean, Length: 111, dtype: float64
Arithmetic_Standard_Dev
9368     9.544256
9369     9.544256
9370     9.544256
9371     9.544256
9372     9.544256
           ...
10496    4.373682
10497    4.373682
10498    4.373682
10499    4.373682
10500    4.373682
Name: Arithmetic_Standard_Dev, Length: 111, dtype: float64
1st_Max_Value
9368     61.9
9369     61.9
9370     61.9
9371     61.9
9372     61.9
         ...
10496    35.7
10497    35.7
10498    35.7
10499    35.7
10500    35.7
Name: 1st_Max_Value, Length: 111, dtype: float64
1st_Max_DateTime
9368     2021-11-06 00:00
9369     2021-11-06 00:00
9370     2021-11-06 00:00
9371     2021-11-06 00:00
9372     2021-11-06 00:00
               ...
10496    2021-10-11 00:00
10497    2021-10-11 00:00
10498    2021-10-11 00:00
10499    2021-10-11 00:00
10500    2021-10-11 00:00
Name: 1st_Max_DateTime, Length: 111, dtype: object
2nd_Max_Value
9368     36.1
9369     36.1
9370     36.1
9371     36.1
9372     36.1
         ...
10496    34.9
10497    34.9
10498    34.9
10499    34.9
10500    34.9
Name: 2nd_Max_Value, Length: 111, dtype: float64
2nd_Max_DateTime
9368     2021-12-06 00:00
9369     2021-12-06 00:00
9370     2021-12-06 00:00
9371     2021-12-06 00:00
9372     2021-12-06 00:00
               ...
10496    2021-08-16 00:00
10497    2021-08-16 00:00
10498    2021-08-16 00:00
10499    2021-08-16 00:00
10500    2021-08-16 00:00
Name: 2nd_Max_DateTime, Length: 111, dtype: object
3rd_Max_Value
9368     32.2
9369     32.2
9370     32.2
9371     32.2
9372     32.2
         ...
10496    32.0
10497    32.0
10498    32.0
10499    32.0
10500    32.0
Name: 3rd_Max_Value, Length: 111, dtype: float64
3rd_Max_DateTime
9368     2021-11-18 00:00
9369     2021-11-18 00:00
9370     2021-11-18 00:00
9371     2021-11-18 00:00
9372     2021-11-18 00:00
               ...
10496    2021-09-23 00:00
10497    2021-09-23 00:00
10498    2021-09-23 00:00
10499    2021-09-23 00:00
10500    2021-09-23 00:00
Name: 3rd_Max_DateTime, Length: 111, dtype: object
4th_Max_Value
9368     30.3
9369     30.3
9370     30.3
9371     30.3
9372     30.3
         ...
10496    29.0
10497    29.0
10498    29.0
10499    29.0
10500    29.0
Name: 4th_Max_Value, Length: 111, dtype: float64
4th_Max_DateTime
9368     2021-11-30 00:00
9369     2021-11-30 00:00
9370     2021-11-30 00:00
9371     2021-11-30 00:00
9372     2021-11-30 00:00
               ...
10496    2021-09-24 00:00
10497    2021-09-24 00:00
10498    2021-09-24 00:00
10499    2021-09-24 00:00
10500    2021-09-24 00:00
Name: 4th_Max_DateTime, Length: 111, dtype: object
99th_Percentile
9368     61.9
9369     61.9
9370     61.9
9371     61.9
9372     61.9
         ...
10496    29.0
10497    29.0
10498    29.0
10499    29.0
10500    29.0
Name: 99th_Percentile, Length: 111, dtype: float64
98th_Percentile
9368     36.1
9369     36.1
9370     36.1
9371     36.1
9372     36.1
         ...
10496    21.0
10497    21.0
10498    21.0
10499    21.0
10500    21.0
Name: 98th_Percentile, Length: 111, dtype: float64
95th_Percentile
9368     32.2
9369     32.2
9370     32.2
9371     32.2
9372     32.2
         ...
10496    15.1
10497    15.1
10498    15.1
10499    15.1
10500    15.1
Name: 95th_Percentile, Length: 111, dtype: float64
90th_Percentile
9368     21.1
9369     21.1
9370     21.1
9371     21.1
9372     21.1
         ...
10496    12.6
10497    12.6
10498    12.6
10499    12.6
10500    12.6
Name: 90th_Percentile, Length: 111, dtype: float64
75th_Percentile
9368     14.2
9369     14.2
9370     14.2
9371     14.2
9372     14.2
         ...
10496     9.4
10497     9.4
10498     9.4
10499     9.4
10500     9.4
Name: 75th_Percentile, Length: 111, dtype: float64
50th_Percentile
9368     9.8
9369     9.8
9370     9.8
9371     9.8
9372     9.8
        ...
10496    7.5
10497    7.5
10498    7.5
10499    7.5
10500    7.5
Name: 50th_Percentile, Length: 111, dtype: float64
10th_Percentile
9368     4.1
9369     4.1
9370     4.1
9371     4.1
9372     4.1
        ...
10496    4.1
10497    4.1
10498    4.1
10499    4.1
10500    4.1
Name: 10th_Percentile, Length: 111, dtype: float64
Local_Site_Name
9368                         Azusa
9369                         Azusa
9370                         Azusa
9371                         Azusa
9372                         Azusa
                   ...
10496    Lancaster-Division Street
10497    Lancaster-Division Street
10498    Lancaster-Division Street
10499    Lancaster-Division Street
10500    Lancaster-Division Street
Name: Local_Site_Name, Length: 111, dtype: object
Address
9368              803 N. LOREN AVE., AZUSA
9369              803 N. LOREN AVE., AZUSA
9370              803 N. LOREN AVE., AZUSA
9371              803 N. LOREN AVE., AZUSA
9372              803 N. LOREN AVE., AZUSA
                       ...
10496    43301 DIVISION ST., LANCASTER, CA
10497    43301 DIVISION ST., LANCASTER, CA
10498    43301 DIVISION ST., LANCASTER, CA
10499    43301 DIVISION ST., LANCASTER, CA
10500    43301 DIVISION ST., LANCASTER, CA
Name: Address, Length: 111, dtype: object
City_Name
9368         Azusa
9369         Azusa
9370         Azusa
9371         Azusa
9372         Azusa
           ...
10496    Lancaster
10497    Lancaster
10498    Lancaster
10499    Lancaster
10500    Lancaster
Name: City_Name, Length: 111, dtype: object
Date_of_Last_Change
9368     2022-07-05
9369     2022-07-05
9370     2022-07-05
9371     2022-07-05
9372     2022-07-05
            ...
10496    2022-05-02
10497    2022-05-02
10498    2022-05-02
10499    2022-05-02
10500    2022-05-02
Name: Date_of_Last_Change, Length: 111, dtype: object

In [5]:
for col in test:
    if len(test[col].value_counts()) > 1:
        print(col)
        print(test[col])

Pollutant_Standard
4    PM25 24-hour 1997
5    PM25 24-hour 2006
6    PM25 24-hour 2012
7     PM25 Annual 1997
8     PM25 Annual 2006
9     PM25 Annual 2012
Name: Pollutant_Standard, dtype: object
Metric_Used
4                        Daily Mean
5                        Daily Mean
6                        Daily Mean
7    Quarterly Means of Daily Means
8    Quarterly Means of Daily Means
9    Quarterly Means of Daily Means
Name: Metric_Used, dtype: object

In [11]:
air_2021['County_Name'].value_counts()

Maricopa           1830
Jefferson          1779
Wayne              1704
Los Angeles        1300
Harris             1222
                   ...
Saline                2
Alexandria City       1
Platte                1
Holt                  1
Saint Francois        1
Name: County_Name, Length: 806, dtype: int64